API_KEYWORD_TYPE_NEW = 'new'
API_KEYWORD_TYPE_SEARCH = 'search'
API_KEYWORD_SEARCH_TYPE_TITLE = 'book_title'
API_KEYWORD_TYPE_HOT = 'hot'
API_KEYWORD_TYPE_NULL = ''

API_LIMIT_ELEMENT_PAGE = 9

API_LIMIT_ELEMENT_SEARCH = 10

API_PATH_ABS= '/home/ubuntu/Comicreader/'

ORDER_STATUS_WAITING = 1
ORDER_STATUS_CONFIRMED = 2
ORDER_STATUS_COMPLETED = 3
ORDER_STATUS_CANCEL = 4